apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-api-token-secret
type: Opaque
stringData:
  email: <path:argocd/data/argocd-vault-plugin/cloudflare#email>
  password: <path:argocd/data/argocd-vault-plugin/cloudflare#api-token>

