apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: gatus-tls
  namespace: gatus
spec:
  secretName: gatus-tls
  issuerRef:
    name: gatus-letsencrypt-prod
  duration: 2160h0m0s
  renewBefore: 360h0m0s  
  dnsNames:
  - gatus.diagon.cloud
